# The name of the project (required) is used for displaying purposes within IO environments and IDEs.
name: flutter_mono_repo

sdkPath: .fvm/flutter_sdk

# A list of paths to local packages that are included in the Melos workspace. Each entry can be a specific path or a glob pattern.
packages:
  - "apps/**"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:
    # Only run the test command when the package has a test directory
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in all packages

  config_fvm:
    run: melos exec -c 6 -- "fvm use 3.10.6"
    description: Run `fvm use 3.10.6` in all packages

  gen:
    run: |
      melos bootstrap
      melos run generate:localization --no-select && \
      melos run generate:build_runner --no-select
    description: Generate files

  generate:localization:
    run: |
      melos exec -c 1 --fail-fast -- \
      flutter pub run easy_localization:generate -S assets/l10n -f keys -O lib/src/l10n -o locale_keys.g.dart
    description: Generate localization
    packageFilters:
      dirExists: assets/l10n

  generate:build_runner:
    run: melos exec -c 6 -- "flutter pub run build_runner build --delete-conflicting-outputs"
    # packageFilters:
    #   ignore: []
